version: '3.8'

services:
  db:
    restart: always
    container_name: bank-api-db
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bank_api
    ports:
      - '3308:3306'
    expose:
      - '3308'